# Generated by Django 6.0 on 2025-12-21 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Nepali mobile number (98/97/96 followed by 8 digits)', regex='^(98|97|96)\\d{8}$')]),
        ),
    ]
