# Generated by Django 5.2.9 on 2025-12-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('blood_units', models.IntegerField(default=1)),
                ('hospital_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donor.donor')),
            ],
            options={
                'verbose_name_plural': 'Donation Histories',
                'ordering': ['-donation_date'],
            },
        ),
    ]
