# Generated by Django 5.2.9 on 2026-01-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='verification_document',
            field=models.ImageField(blank=True, null=True, upload_to='donor_documents/'),
        ),
        migrations.AddField(
            model_name='donor',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
    ]
