# Generated by Django 6.0 on 2026-01-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_type_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donor',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='id_docs/'),
        ),
    ]
