# Generated by Django 5.2.9 on 2026-01-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_donor_is_verified_donor_verification_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='city',
            field=models.CharField(default='Biratnagar', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
